# .github/notify-twitter.yml
name: Notify twitter

permissions: read-all

on:
  workflow_dispatch: null
  release:
    # publishes is fired when a release is created programmatically
    # https://stackoverflow.com/questions/59319281/github-action-different-between-release-created-and-published
    # must be created with a PAT if automated
    types: [published]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: nearform-actions/github-action-notify-twitter@master
        with:
          message: |
            ${{ github.event.repository.name }} ${{ github.event.release.tag_name }} has been released. Check out the release notes: ${{ github.event.release.html_url }}
          twitter-app-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_CONSUMER_SECRET_KEY }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_TOKEN_SECRET }}
